set_unless[:sphinx][:version]="sphinx-0.9.8.1"
set_unless[:sphinx][:url]="http://www.sphinxsearch.com/downloads/#{sphinx[:version]}.tar.gz"
set_unless[:sphinx][:path]="/opt/#{sphinx[:version]}"
set_unless[:sphinx][:src_path]="/opt/src"
set_unless[:sphinx][:tar_file]="#{sphinx[:src_path]}/#{sphinx[:version]}.tar.gz"
set_unless[:sphinx][:configure_options]="--with-libstemmer"
set_unless[:sphinx][:tar_file_checksum]="ef69b2b52381173da92bf2df79dfc8c5271c4b3f156c356bb4ef82ca035dc013"
