set[:ree][:version] = "ruby-enterprise-1.8.7-2009.10"
set[:ree][:url] = "http://rubyforge.org/frs/download.php/66162/#{ree[:version]}.tar.gz"
set[:ree][:path] = "/opt/#{ree[:version]}"
set[:ree][:src_path] = "/opt/src"
set[:ree][:tar_file] = "#{ree[:src_path]}/#{ree[:version]}.tar.gz"
set[:ree][:gem_path] = "#{ree[:path]}/bin/gem"
set[:ree][:configure_options] = "--dont-install-useful-gems --auto #{ree[:path]}"
